title: Jean Schindler
logo: profile-pic%20(2).png
description: Welcome to my data science portfolio! This document provides an overview of my key projects, showcasing my skills in machine learning, natural language processing, time series forecasting, and deep learning. Each project includes a detailed description of the methodology, tools, and technologies used, as well as the results and key takeaways.
# show_downloads: true
theme: jekyll-theme-minimal
